export const items = [
    {
        name: 'African Doughnut Mix',
        price: '30',
        favourite: false,
        description: 'Rare Eat Puff Puff Mix can be made into a deep-fried dough. They are made from yeast dough, shaped into balls and deep-fried until golden brown. It has a doughnut-like texture but slightly o akjfaf',
        image: require('./assets/images/PuffPuff.png'),
    },
    {
        name: 'African Doughnut Mix',
        price: '30',
        favourite: false,
        description: 'Rare Eat Puff Puff Mix can be made into a deep-fried dough. They are made from yeast dough, shaped into balls and deep-fried until golden brown. It has a doughnut-like texture but slightly o akjfaf',
        image: require('./assets/images/PuffPuff.png'),
    },
    {
        name: 'Chicken Stew',
        price: '30',
        favourite: false,
        description: 'Rare Eat Puff Puff Mix can be made into a deep-fried dough. They are made from yeast dough, shaped into balls and deep-fried until golden brown. It has a doughnut-like texture but slightly o akjfaf',
        image: require('./assets/images/Stew.png'),
    },
    {
        name: 'Asaro(Yam)',
        price: '30',
        favourite: true,
        description: 'Rare Eat Puff Puff Mix can be made into a deep-fried dough. They are made from yeast dough, shaped into balls and deep-fried until golden brown. It has a doughnut-like texture but slightly o akjfaf',
        image: require('./assets/images/MoiMoi.png'),
    },
    {
        name: 'Efo Riro',
        price: '30',
        favourite: false,
        description: 'Rare Eat Puff Puff Mix can be made into a deep-fried dough. They are made from yeast dough, shaped into balls and deep-fried until golden brown. It has a doughnut-like texture but slightly o akjfaf',
        image: require('./assets/images/EfoRiro.png'),
    },
    {
        name: 'African Doughnut Mix',
        price: '30',
        favourite: true,
        description: 'Rare Eat Puff Puff Mix can be made into a deep-fried dough. They are made from yeast dough, shaped into balls and deep-fried until golden brown. It has a doughnut-like texture but slightly o akjfaf',
        image: require('./assets/images/PuffPuff.png'),
    },
    {
        name: 'African Doughnut Mix',
        price: '30',
        favourite: false,
        description: 'Rare Eat Puff Puff Mix can be made into a deep-fried dough. They are made from yeast dough, shaped into balls and deep-fried until golden brown. It has a doughnut-like texture but slightly o akjfaf',
        image: require('./assets/images/PuffPuff.png'),
    },
    {
        name: 'African Doughnut Mix',
        price: '30',
        favourite: false,
        description: 'Rare Eat Puff Puff Mix can be made into a deep-fried dough. They are made from yeast dough, shaped into balls and deep-fried until golden brown. It has a doughnut-like texture but slightly o akjfaf',
        image: require('./assets/images/PuffPuff.png'),
    },
]